spring:
  application:
    name: petmily-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/petmily
    username: postgres
    password: lee3040h
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql
      encoding: UTF-8
  
  security:
    jwt:
      secret: myVerySecureJWTSecretKeyForPetmilyApplication1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
      expiration: 86400000 # 24 hours
  
  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
          client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
          scope:
            - email
            - profile
        facebook:
          client-id: ${FACEBOOK_CLIENT_ID:your-facebook-client-id}
          client-secret: ${FACEBOOK_CLIENT_SECRET:your-facebook-client-secret}
          scope:
            - email
            - public_profile
      provider:
        google:
          authorization-uri: https://accounts.google.com/o/oauth2/auth
          token-uri: https://oauth2.googleapis.com/token
          user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
          user-name-attribute: id
        facebook:
          authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
          token-uri: https://graph.facebook.com/v18.0/oauth/access_token
          user-info-uri: https://graph.facebook.com/v18.0/me?fields=id,name,email,picture
          user-name-attribute: id

server:
  port: 8080

logging:
  level:
    com.petmily.backend: DEBUG
    org.springframework.security: DEBUG

